version: "3.8"
services:
  app1:
    build: .
    volumes:
      - .:/django
    ports:
      - 8000:8000
    image: app:django
    container_name: django_container1
    command: gunicorn core.wsgi -b 0.0.0.0:8000
    depends_on:
        - db
  db:
    image: postgres
    volumes:
        - ./data/db:/var/lib/postgresql/data
    environment:
        - POSTGRES_DB=eshop
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=kirgizia
    container_name: postgres_db1