# Generated by Django 3.2.4 on 2021-07-08 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_order_price_with_discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=50),
        ),
    ]
