# Generated by Django 3.2.4 on 2021-07-17 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_promocode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promocode',
            name='id',
        ),
        migrations.AlterField(
            model_name='promocode',
            name='name',
            field=models.CharField(db_index=True, max_length=500, primary_key=True, serialize=False, unique=True),
        ),
    ]
