# Generated by Django 3.2.4 on 2021-07-08 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='variation',
            name='discount',
            field=models.IntegerField(default=0),
        ),
    ]
