# Generated by Django 3.2.4 on 2021-07-08 08:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20210708_0709'),
    ]

    operations = [
        migrations.AddField(
            model_name='variation',
            name='creation_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
