# Generated by Django 3.2.4 on 2021-07-08 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_variation_creation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variation',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
